version: "3"
services:
  app:
    container_name: botchatapp-full
    image: index.docker.io/guppy285/botchatapp-full:latest
    networks:
      - local_net
    ports:
      - "8080:8080"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.docker/config.json:/config.json
    command: --interval 30
networks:
  local_net:
    driver: bridge
