name: Build Containers for Prod & Push to Dockerhub

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-deploy-back:
    name: Build and Deploy Back-end
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
 
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        file: Dockerfile
        push: true
        tags: guppy285/botchatapp-back:latest

  build-and-deploy-front:
    name: Build and Deploy Front-End
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
 
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        file: public/Dockerfile
        push: true
        tags: guppy285/botchatapp-front:latest
